### ISSUE TITLE
Finalize HW

### ISSUE THREAD

**Issue by odellsj** [IntroToCode/Spring21_Recipes_Codemates6#27]
## 💬 Discussion topic

Listing Acceptance Criteria to finalize HW

## ❗ Potential issues

General confusion

## 👥 People to consult

Team Codemates6

## 📃 Details

Acceptance Criteria:
1) Your Codemates team used Issues to clearly delineate work (30%)
Was there stated acceptance criteria?
Were ideas communicated, debated, and resolved in the Pull Requests?
Have related issues been closed when resolved?

2) Your Codemates team used Pull Requests to discuss solutions (60%)
Did every team member commit to the Pull Requests? (comments are not commits)
Did the team use the reviews feature of GitHub to get explicit approval? 
Did at least TWO people approve each Pull Request? 

3) Work collaboratively on changes until objective is completed (10%)
Are there (3) fully completed recipes on the main/master branch?
Was there conversation, disagreement, discussion of style in the Pull Requests?

**Comment by odellsj** [comment]
For ensuring at least TWO people approved each pull request -- add your +1 emoji to the latest approver in the pull request

**Comment by nbretschneider** [comment]
Finalized all the merges into the main branch - done!
