### ISSUE TITLE
Complete breakfast menu

### ISSUE THREAD

**Issue by ShotaroIshizuka** [IntroToCode/Spring21_Recipes_Codemates6#3]
## 💬 Discussion topic

Burrito

## ❗ Potential issues

Details are not there

## 👥 People to consult

@ericsassano , @minku1016 , @nbretschneider , @odellsj 

## 📃 Details

We need a tasty Burrito

**Comment by nbretschneider** [comment]
Yes I think that is a great idea! Let's do breakfast burritos

**Comment by odellsj** [comment]
I can start adding some ingredients that might be needed

**Comment by odellsj** [comment]
Acceptance Criteria:

Name + Servings: Steve
Ingredients: Eric
Steps for Preparation: Nik
Time to Prepare: Min
Equipment needed: Shotaro
main

**Comment by minku1016** [comment]
thanks for the acceptance criteria - we are getting to the finish line!

**Comment by ShotaroIshizuka** [comment]
Acceptance Criteria fulfilled
