### ISSUE TITLE
Vegetarian Options

### ISSUE THREAD

**Issue by ericsassano** [IntroToCode/Spring21_Recipes_Codemates6#5]
## 💬 Discussion topic

Should we have a vegetarian option for dinner?

## ❗ Potential issues

Text

## 👥 People to consult

@nbretschneider @odellsj @minku1016 @ShotaroIshizuka 

## 📃 Details

Text

**Comment by ShotaroIshizuka** [comment]
Yes that's more inclusive!

**Comment by nbretschneider** [comment]
Yes I think this is very much in line with people at Berkeley, great idea!
