### ISSUE TITLE
We need a dinner meal to build a recipe around

### ISSUE THREAD

**Issue by odellsj** [IntroToCode/Spring21_Recipes_Codemates6#6]
## 💬 Discussion topic

Pick a dinner meal

## ❗ Potential issues

We might have a lot of different ideas

## 👥 People to consult

Team Codemates 6

## 📃 Details

@nbretschneider @minku1016 @ericsassano @ShotaroIshizuka  please review and suggest ideas

**Comment by ShotaroIshizuka** [comment]
Rib fried rice?

**Comment by odellsj** [comment]
@nbretschneider just created a dinner branch, let's work in there

**Comment by odellsj** [comment]
Acceptance Criteria:

Name + Servings: Steve
Ingredients: Eric
Steps for Preparation: Nik
Time to Prepare: Min
Equipment needed: Shotaro
main

**Comment by odellsj** [comment]
@ShotaroIshizuka we have Rib Fried Rice for Lunch. How about a salad for dinner?

**Comment by ShotaroIshizuka** [comment]
Sounds great!

**Comment by nbretschneider** [comment]
Ok great

**Comment by minku1016** [comment]
agreed. salad for dinner

**Comment by nbretschneider** [comment]
Done now after the merge
