### ISSUE TITLE
Create Lunch Branch and develop lunch recipe

### ISSUE THREAD

**Issue by odellsj** [IntroToCode/Spring21_Recipes_Codemates6#9]
## 💬 Discussion topic

Opening an issue to track completion of the lunch recipe creation in the lunch branch, and subsequent merge to main

## ❗ Potential issues

General confusion as we try to figure this out

## 👥 People to consult

Team Codemates6

## 📃 Details

@nbretschneider @ericsassano @ShotaroIshizuka @minku1016

**Comment by odellsj** [comment]
Acceptance Criteria:

Name + Servings: Steve
Ingredients: Eric
Steps for Preparation: Nik
Time to Prepare: Min
Equipment needed: Shotaro
main

**Comment by minku1016** [comment]
we can come up with a recipe for salad.

EDIT: lunch menu is rib fried rice

**Comment by nbretschneider** [comment]
Done
